version: '3'
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true
services:
  metabase:
    image: metabase/metabase:latest
    container_name: ${PROJECT_NAME}-metabase
    env_file:
      - .env
    ports:
      - ${METABASE_PORT:-3000}:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DBNAME:-metabase}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER:-postgres}
      MB_DB_PASS: ${POSTGRES_PASSWORD:-postgres}
      MB_DB_HOST: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy