version: "3"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true

services:
  
  jupyterlab:
    image: ${JUPYTERLAB_IMAGE:-jupyterlab:3.3.1}
    container_name: ${PROJECT_NAME}-jupyterlab
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - .env
    ports:
      - ${JUPYTERLAB_PORT:-8888}:8888
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  spark-master:
    image: ${SPARK_MASTER_IMAGE:-spark-master:3.3.1}
    container_name: ${PROJECT_NAME}-spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    expose:
      - "7077"
    ports:
      - "${SPARK_MASTER_WEBUI_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  spark-worker-1:
    image: ${SPARK_WORKER_IMAGE:-spark-worker:3.3.1}
    container_name: ${PROJECT_NAME}-spark-worker-1
    depends_on:
      - spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-1G}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-1}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    env_file:
      - .env
    ports:
      - ${SPARK_WORKER_WEBUI_PORT:-8081}:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

    
