version: 2

sources:
  - name: agri_data
    database: "{{ target.project }}"
    schema: "{{ target.schema }}"
    tables:
      - name: dim_farm
        description: Farm dimension containing information about agricultural farms
        columns:
          - name: farm_id
            description: Unique identifier for the farm
            tests:
              - unique
              - not_null
          - name: farm_name
            description: Name of the farm
          - name: location
            description: Geographic location of the farm
          - name: size_hectares
            description: Size of the farm in hectares
          - name: established_date
            description: Date when the farm was established

      - name: dim_crop
        description: Crop dimension containing information about different crops
        columns:
          - name: crop_id
            description: Unique identifier for the crop
            tests:
              - unique
              - not_null
          - name: crop_name
            description: Name of the crop
          - name: crop_type
            description: Type or category of the crop
          - name: growing_season
            description: Season when the crop is typically grown
          - name: water_needs
            description: Water requirements for the crop

      - name: dim_weather
        description: Weather dimension containing meteorological data
        columns:
          - name: weather_id
            description: Unique identifier for the weather record
            tests:
              - unique
              - not_null
          - name: date
            description: Date of the weather record
          - name: location
            description: Location where the weather was recorded
          - name: temperature
            description: Temperature in Celsius
          - name: precipitation
            description: Precipitation in millimeters
          - name: humidity
            description: Humidity percentage

      - name: dim_soil
        description: Soil dimension containing information about soil characteristics
        columns:
          - name: soil_id
            description: Unique identifier for the soil record
            tests:
              - unique
              - not_null
          - name: farm_id
            description: Reference to the farm
          - name: ph_level
            description: pH level of the soil
          - name: nutrient_content
            description: Nutrient content in the soil
          - name: texture
            description: Texture of the soil
          - name: organic_matter
            description: Percentage of organic matter in the soil

      - name: dim_harvest
        description: Harvest dimension containing information about crop harvests
        columns:
          - name: harvest_id
            description: Unique identifier for the harvest
            tests:
              - unique
              - not_null
          - name: farm_id
            description: Reference to the farm
          - name: crop_id
            description: Reference to the crop
          - name: harvest_date
            description: Date of the harvest
          - name: yield_amount
            description: Amount harvested
          - name: quality_grade
            description: Quality grade of the harvest

      - name: fact_production
        description: Production facts containing agricultural production data
        columns:
          - name: production_id
            description: Unique identifier for the production record
            tests:
              - unique
              - not_null
          - name: farm_id
            description: Reference to the farm
          - name: crop_id
            description: Reference to the crop
          - name: date
            description: Production date
          - name: quantity_produced
            description: Quantity produced
          - name: cost
            description: Production cost

      - name: fact_yield
        description: Yield facts containing crop yield data
        columns:
          - name: yield_id
            description: Unique identifier for the yield record
            tests:
              - unique
              - not_null
          - name: farm_id
            description: Reference to the farm
          - name: crop_id
            description: Reference to the crop
          - name: harvest_id
            description: Reference to the harvest
          - name: yield_per_hectare
            description: Yield per hectare
          - name: year
            description: Year of the yield

      - name: fact_sustainability
        description: Sustainability facts containing environmental impact data
        columns:
          - name: sustainability_id
            description: Unique identifier for the sustainability record
            tests:
              - unique
              - not_null
          - name: farm_id
            description: Reference to the farm
          - name: date
            description: Date of the sustainability record
          - name: water_usage
            description: Water usage in liters
          - name: carbon_footprint
            description: Carbon footprint in CO2 equivalent
          - name: pesticide_usage
            description: Pesticide usage in kilograms

models:
  - name: stg_farm
    description: Staging model for farm dimension
    columns:
      - name: farm_id
        description: Unique identifier for the farm
        tests:
          - unique
          - not_null

  - name: stg_crop
    description: Staging model for crop dimension
    columns:
      - name: crop_id
        description: Unique identifier for the crop
        tests:
          - unique
          - not_null

  - name: stg_weather
    description: Staging model for weather dimension
    columns:
      - name: weather_id
        description: Unique identifier for the weather record
        tests:
          - unique
          - not_null

  - name: stg_soil
    description: Staging model for soil dimension
    columns:
      - name: soil_id
        description: Unique identifier for the soil record
        tests:
          - unique
          - not_null

  - name: stg_harvest
    description: Staging model for harvest dimension
    columns:
      - name: harvest_id
        description: Unique identifier for the harvest
        tests:
          - unique
          - not_null

  - name: stg_production
    description: Staging model for production facts
    columns:
      - name: production_id
        description: Unique identifier for the production record
        tests:
          - unique
          - not_null

  - name: stg_yield
    description: Staging model for yield facts
    columns:
      - name: yield_id
        description: Unique identifier for the yield record
        tests:
          - unique
          - not_null

  - name: stg_sustainability
    description: Staging model for sustainability facts
    columns:
      - name: sustainability_id
        description: Unique identifier for the sustainability record
        tests:
          - unique
          - not_null 