version: '3.6'
networks:
  default:
    name: agri_data_pipeline-network
    external: true
services:
  producer:
      build:
        context: ../../streaming_pipeline
      container_name: agri_data_producer
      hostname: producer
      command: python /home/streaming_pipeline/data_producer.py
      working_dir: /home/streaming_pipeline
      volumes:
        - ../../streaming_pipeline:/home/streaming_pipeline
      environment:
        - NUM_MESSAGES=${NUM_MESSAGES}
        - MESSAGE_DELAY=${MESSAGE_DELAY}
        - KAFKA_BROKER=broker:29092
      extra_hosts:
        - "broker:172.26.0.3"
      restart: on-failure
  
  consumer:
      build:
        context: ../../streaming_pipeline
      container_name: agri_data_consumer
      hostname: consumer
      restart: on-failure
      command: python -u /home/streaming_pipeline/data_consumer.py
      working_dir: /home/streaming_pipeline
      volumes:
        - ../../streaming_pipeline:/home/streaming_pipeline
        - /tmp:/tmp
      environment:
        - MAX_MESSAGES=${MAX_MESSAGES}
        - BATCH_SIZE=${BATCH_SIZE}
        - POLL_TIMEOUT=${POLL_TIMEOUT}
        - GCS_TEMP_BLOB_PATH=${GCS_TEMP_BLOB_PATH}
        - KAFKA_BROKER=broker:29092
        - CONSUMER_GROUP=agri_data_consumer_new
        - AUTO_OFFSET_RESET=earliest
      extra_hosts:
        - "broker:172.26.0.3"
      depends_on:
        - producer
        